
// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.9.0.
//
// This code was generated with the following options:
//
//  {'epsilon': 1e-14,
//   'output_directory': '.',
//   'profile': False,
//   'scalar_type': 'float64',
//   'sum_factorization': False,
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'ufl_file': ['forms.py'],
//   'verbosity': 30,
//   'visualise': False}

#pragma once
#include <ufcx.h>

#ifdef __cplusplus
extern "C" {
#endif

extern ufcx_integral integral_2d519e4276f88e572667d8b1de62059aa34ae8e8;

extern ufcx_integral integral_2d14a3d074fec352aa51ff6b20b4c962892c2ce5;

extern ufcx_integral integral_dbcc567cec8e9937eb97d72e7603775744b33bdf;

extern ufcx_integral integral_ebca116e441592a6cd75fe80a3f49496a3f74cb8;

extern ufcx_form form_f3fdfeb99ad938c39ff5223fa92a1c9355f3e3a1;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_forms_a;


extern ufcx_form form_da618a8bc9bcd8f64ef6522817b79f422270bc32;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_forms_L;


#ifdef __cplusplus
}
#endif
