
// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.9.0.
//
// This code was generated with the following options:
//
//  {'epsilon': 1e-14,
//   'output_directory': '.',
//   'profile': False,
//   'scalar_type': 'float64',
//   'sum_factorization': False,
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'ufl_file': ['forms.py'],
//   'verbosity': 30,
//   'visualise': False}

#pragma once
#include <ufcx.h>

#ifdef __cplusplus
extern "C" {
#endif

extern ufcx_integral integral_7c6e3eb21f74e2b18edbdae8b193d51b002e3bd4;

extern ufcx_integral integral_c611e2582fe414510adefdba042bcb55af8cdf95;

extern ufcx_integral integral_0762a9babbc0460f61041de7e68c012a4947abec;

extern ufcx_form form_916d083cac32dd7b743e3bde4b6ed1d40edc9575;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_forms_a;


extern ufcx_form form_89f7143d2635758711348474c5b500f506f99f49;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_forms_L;


#ifdef __cplusplus
}
#endif
